server:
  websocket:
    port: 8080
    pingPeriodSeconds: 60
    readBufferSize: 1024
    writeBufferSize: 1024
    allowOrigin: "^(http|https)://(\\w+)\\.github\\.com"
  http:
    port: 8888
database:
  default:
    host: 127.0.0.1
logger:
  path: "/log/freeway/info.log"
  level: info